artifact_uri: /Users/stamatiosorphanos/Desktop/Stress_Detection/Heart Rate Prediction
  to Monitor Stress Level/244011781004297121/40651655e6fe4d8ab1eb8c97efef1dac/artifacts
end_time: 1749899423224
entry_point_name: ''
experiment_id: '244011781004297121'
lifecycle_stage: active
run_id: 40651655e6fe4d8ab1eb8c97efef1dac
run_name: wise-jay-128
run_uuid: 40651655e6fe4d8ab1eb8c97efef1dac
source_name: ''
source_type: 4
source_version: ''
start_time: 1749899419217
status: 3
tags: []
user_id: stamatiosorphanos
