artifact_location: /Users/stamatiosorphanos/Desktop/Stress_Detection/Stress Predict/0
creation_time: 1749899423258
experiment_id: '0'
last_update_time: 1749899423258
lifecycle_stage: active
name: Default
