artifact_location: /Users/stamatiosorphanos/Desktop/Stress_Detection/Stress Predict/248656833100231528
creation_time: 1749899423260
experiment_id: '248656833100231528'
last_update_time: 1749899423260
lifecycle_stage: active
name: Logistic Regression
