stages:
  - dockerize
  - deploy

variables:
  IMAGE_NAME: "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME"

dockerize:
  stage: dockerize
  image: docker
  script:
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    - docker pull $IMAGE_NAME || true
    - docker build --cache-from $IMAGE_NAME -t "$IMAGE_NAME" .
    - docker push "$IMAGE_NAME"
    - docker logout $CI_REGISTRY
  tags:
    - docker
  only:
    - tags
    - branches

deploy_staging:
  stage: deploy
  variables:
    HOST: $STAGING_HOST
    USER: $STAGING_USER
    URL: $URL
  before_script:
    - eval `ssh-agent -s`
    - echo "$STAGING_PRIVATE_KEY" | tr -d '\r' | ssh-add - 
    - ssh-keyscan $HOST >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - echo "Deployment to ($HOST)"
    - echo "URL=$URL" >> .env
    - docker context create remote --docker "host=ssh://$USER@$HOST"
    - echo "$CI_JOB_TOKEN" | docker --context remote login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    - docker --context remote compose -f docker-compose.staging.yaml up -d --pull always
    - docker --context remote image prune -f
    - docker --context remote logout $CI_REGISTRY
  tags:
    - docker
  only:
    - tags
    - branches
  when: manual
