stages:
  - dockerize
  - deploy

variables:
  IMAGE_NAME: "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME"

dockerize:
  stage: dockerize
  image: docker
  before_script:
    - chmod +x setup_env.sh
    - ./setup_env.sh
  script:
    - docker build -t "$IMAGE_NAME" .
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - echo "$IMAGE_NAME"
    - docker push "$IMAGE_NAME"
  tags:
    - docker
  only:
    - tags
    - branches
  when: manual

deploy_staging:
  stage: deploy
  variables:
    HOST: "ai4work1.cbml-unipi.gr"
    USER: "ubuntu"
    APP_DIR: "/apps/stress-detector"
  before_script:
    - eval `ssh-agent -s`
    - echo "$STAGING_PRIVATE_KEY" | tr -d '\r' | ssh-add - 
  script:
    - echo "Deployment to ($HOST)"
    - scp -oStrictHostKeyChecking=no -i id_rsa deployment/docker-compose.yaml $USER@$HOST:$APP_DIR
    - ssh -oStrictHostKeyChecking=no -i id_rsa $USER@$HOST 'bash -s' < deployment/deploy.sh $CI_REGISTRY $IMAGE_NAME $CI_JOB_TOKEN $APP_DIR
  environment:
    name: staging
    url: https://ai4work1.cbml-unipi.gr
  tags:
    - docker
  only:
    - tags
    - branches
  when: manual
