artifact_uri: /Users/stamatiosorphanos/Desktop/Stress_Detection/Stress Predict/248656833100231528/c24aee20d3484f1e9dbcae7bf82380f2/artifacts
end_time: 1749899816150
entry_point_name: ''
experiment_id: '248656833100231528'
lifecycle_stage: active
run_id: c24aee20d3484f1e9dbcae7bf82380f2
run_name: unique-fawn-388
run_uuid: c24aee20d3484f1e9dbcae7bf82380f2
source_name: ''
source_type: 4
source_version: ''
start_time: 1749899814374
status: 3
tags: []
user_id: stamatiosorphanos
