artifact_location: /Users/stamatiosorphanos/Desktop/Stress_Detection/SWELL Dataset/562279980789960444
creation_time: 1749899426179
experiment_id: '562279980789960444'
last_update_time: 1749899426179
lifecycle_stage: active
name: Logistic Regression
