artifact_uri: /Users/stamatiosorphanos/Desktop/Stress_Detection/SWELL Dataset/562279980789960444/c52bdfdf9f6941b183bd9eb681bbd32c/artifacts
end_time: 1749899821835
entry_point_name: ''
experiment_id: '562279980789960444'
lifecycle_stage: active
run_id: c52bdfdf9f6941b183bd9eb681bbd32c
run_name: grandiose-flea-760
run_uuid: c52bdfdf9f6941b183bd9eb681bbd32c
source_name: ''
source_type: 4
source_version: ''
start_time: 1749899817310
status: 3
tags: []
user_id: stamatiosorphanos
