artifact_location: /Users/stamatiosorphanos/Desktop/Stress_Detection/Heart Rate Prediction
  to Monitor Stress Level/244011781004297121
creation_time: 1749899419063
experiment_id: '244011781004297121'
last_update_time: 1749899419063
lifecycle_stage: active
name: Logistic Regression
