artifact_location: /Users/stamatiosorphanos/Desktop/Stress_Detection/Heart Rate Prediction
  to Monitor Stress Level/0
creation_time: 1749899419058
experiment_id: '0'
last_update_time: 1749899419058
lifecycle_stage: active
name: Default
