artifact_uri: /Users/stamatiosorphanos/Desktop/Stress_Detection/SWELL Dataset/562279980789960444/47cd3ca046e34c1a93d9b9efc71fbd5b/artifacts
end_time: 1749899430550
entry_point_name: ''
experiment_id: '562279980789960444'
lifecycle_stage: active
run_id: 47cd3ca046e34c1a93d9b9efc71fbd5b
run_name: unruly-hen-572
run_uuid: 47cd3ca046e34c1a93d9b9efc71fbd5b
source_name: ''
source_type: 4
source_version: ''
start_time: 1749899426180
status: 3
tags: []
user_id: stamatiosorphanos
