artifact_location: /Users/stamatiosorphanos/Desktop/Stress_Detection/SWELL Dataset/0
creation_time: 1749899426176
experiment_id: '0'
last_update_time: 1749899426176
lifecycle_stage: active
name: Default
