artifact_uri: /Users/stamatiosorphanos/Desktop/Stress_Detection/Stress Predict/248656833100231528/e77cbadadf4b4f5982caf35413a3f7c8/artifacts
end_time: 1749899425080
entry_point_name: ''
experiment_id: '248656833100231528'
lifecycle_stage: active
run_id: e77cbadadf4b4f5982caf35413a3f7c8
run_name: bedecked-dog-834
run_uuid: e77cbadadf4b4f5982caf35413a3f7c8
source_name: ''
source_type: 4
source_version: ''
start_time: 1749899423261
status: 3
tags: []
user_id: stamatiosorphanos
